Repository Teaching-projects/SZE-MOSZE-2020-plusplusplus, pull requests merged in 2020-11, with the labels that each got.

#16 Documentation
  README.md
  doxygenconf
  json.h
  jsonFileReadError.h
  jsonParseError.h
  loop.h
  player.h
Labels: documentation

#18 Refactor
  Hero.cpp
  Hero.h
  JSON.cpp
  JSON.h
  Makefile
  Monster.cpp
  Monster.h
  README.md
  Unit.cpp
  Unit.h
  jsonFileReadError.h
  jsonParseError.h
  loop.cpp
  loop.h
  main.cpp
  player.cpp
  player.h
  run_all.sh
  scenarios/expected_results.csv
  scenarios/scenario1.json
  scenarios/scenario2.json
  tests/CMakeLists.txt
  tests/JSONTest.cpp
  tests/jsonTest.cpp
  units/Blood_Raven.json
  units/Dark_Wanderer.json
  units/Fallen.json
  units/Zombie.json
  units/expected_results.csv
  units/unit1.json
  units/unit2.json
  units/unit3.json
Labels: enhancement

#23 Json array
  Hero.cpp
  Hero.h
  JSON.cpp
  JSON.h
  Monster.cpp
  Monster.h
  README.md
  Unit.cpp
  Unit.h
  doxygenconf
  main.cpp
  scenarios/scenario1.json
  scenarios/scenario2.json
  tests/JSONTest.cpp
Labels: documentation, enhancement, test necessary

#28 Defense
  .gitignore
  Hero.cpp
  Hero.h
  JSON.h
  Makefile
  Monster.cpp
  Monster.h
  README.md
  Unit.cpp
  Unit.h
  scenarios/expected_results.csv
  tests/heroTest.cpp
  tests/monsterTest.cpp
  tests/unitTest.cpp
  units/Blood_Raven.json
  units/Dark_Wanderer.json
  units/Fallen.json
  units/Zombie.json
Labels: enhancement

#29 Damage
  Damage.h
  Hero.cpp
  Hero.h
  JSON.h
  Makefile
  Monster.cpp
  Monster.h
  README.md
  Unit.cpp
  Unit.h
  scenarios/expected_results.csv
  tests/heroTest.cpp
  tests/monsterTest.cpp
  tests/unitTest.cpp
  units/Blood_Raven.json
  units/Dark_Wanderer.json
Labels: enhancement
